### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Egor179** [Samlis/AliasIsolationForEpicGamesStore#1]
Oh, it seems that it still doesn't work, or I'm doing something wrong.
Anti-aliasing selected by SMAA T1x. Chromatic Aberration disabled. Motion blur enabled.
When you press CTRL + INSERT, the screen jerks, but there is no anti-aliasing
https://www.youtube.com/watch?v=Pge0-mckLgU

PS Sorry for Russian

**Comment by Samlis** [comment]
no no, my Russian friend, you can't have the game running when you execute the cmd. The CMD will run the game :) Close the game and run. You should see the logo when you load a save :)

let me know

**Comment by Egor179** [comment]
> no no, my Russian friend, you can't have the game running when you execute the cmd. The CMD will run the game :) Close the game and run. You should see the logo when you load a save :)
> 
> let me know

It still doesn't seem to work
https://www.youtube.com/watch?v=091yc-o2qRk

**Comment by Samlis** [comment]
Can you put quotes around the path? like this:

epicisolation.cmd "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"

**Comment by Egor179** [comment]
> Can you put quotes around the path? like this:
> 
> epicisolation.cmd "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"

It did not help
https://www.youtube.com/watch?v=fLuyYz4U-9M&feature=youtu.be

**Comment by Samlis** [comment]
Hm, it's not executing the application. The CMD is supposed to do that. You are on Windows Vista?
Can you try running this from the cmd:
cmd /C "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"
If that executes the game, please open the epicisolation.cmd and replace the 1st line with the above command and try again.

thx

**Comment by Egor179** [comment]
No, I'm using Windows 10 LTSC x64
https://youtu.be/LfFNJ35TQtk

**Comment by Egor179** [comment]
> Hm, it's not executing the application. The CMD is supposed to do that.
> I think I know why. Can you try running this from the cmd:
> cmd /C "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"
> If that executes the game, please open the epicisolation.cmd and replace the 1st line with the above command and try again.
> 
> thx

No, I'm using Windows 10 LTSC x64

**Comment by Egor179** [comment]
> Hm, it's not executing the application. The CMD is supposed to do that.
> I think I know why. Can you try running this from the cmd:
> cmd /C "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"
> If that executes the game, please open the epicisolation.cmd and replace the 1st line with the above command and try again.
> 
> thx

It looks like the problem is different: the process starts, but immediately turns off, after a while Epic Games starts it itself
https://www.youtube.com/watch?v=kdEqDB2yB2I&feature=youtu.be

**Comment by Egor179** [comment]
Also I noticed that there is synchronization with the cloud

**Comment by Samlis** [comment]
oh, then that is definitely a problem (different one, but a big one). Maybe remove reshade mod and try? Keep Epic open. The AI.exe should just start the game, it does for me, even from command-line. Try removing any mods and work with the raw installation.

**Comment by Egor179** [comment]
> oh, the process closing is definitely a problem (different one, but a big one). Maybe remove reshade mod and try? Keep Epic open. The AI.exe should just start the game, it does for me, even from command-line. Try removing any mods and work with the raw installation.

Curse looks like protection from piracy
https://www.youtube.com/watch?v=ZlDq0HBNKIs

**Comment by Samlis** [comment]
oh, what is throwing that error? If this is some external program then I can't help with that, maybe disable it? Looks like your setup is correct now in terms of the mod. You should really try to remove reshade from there. On https://github.com/aliasIsolation/aliasIsolation it says there are conflicts with ReShade. Try a basic installation, with no other mods.

**Comment by Egor179** [comment]
> о, что вызывает эту ошибку? Если это какая-то внешняя программа, то я не могу с этим помочь, может, отключить? Похоже, ваша настройка теперь верна с точки зрения мода. Вам действительно стоит попытаться удалить оттуда повторную заливку. На https://github.com/aliasIsolation/aliasIsolation говорится о конфликтах с ReShade. Попробуйте базовую установку, без других модов.

I did not experience any problems on the steam version, and Reshade also worked, but it was necessary to turn off the steam, first the mod launcher was launched, then the steam and then the game, here it is somehow different.
I will verify the files and try again

**Comment by Egor179** [comment]
> oh, what is throwing that error? If this is some external program then I can't help with that, maybe disable it? Looks like your setup is correct now in terms of the mod. You should really try to remove reshade from there. On https://github.com/aliasIsolation/aliasIsolation it says there are conflicts with ReShade. Try a basic installation, with no other mods.

No, no way. Maybe your launcher is not updated? :D
And Epic Launcher doesn't work on the latest version?
https://youtu.be/4FdB7beCJuU

**Comment by Samlis** [comment]
So what is the state now?

1. So the game now runs when you execute AI.exe from cmd and the process doesn't crash? If so, that's good.
2. Does epicisolation.cmd launch the game without crashing?
3. Does epicisolation.cmd at any point say "Injecting the DLL" and then "DLL already injected!" ?

**Comment by Egor179** [comment]
> As far as I know, my Epic is up-to-date, I did not disable updates, I think it updates automatically - never asked me about it.
> 
> So what is the state now?
> 
> 1. The game now runs when you execute AI.exe from cmd and the process doesn't crash? If so, that's good.
> 2. Does epicisolation.cmd launch the game without crashing?
> 3. Does epicisolation.cmd at any point say "Injecting the DLL" and then "DLL already injected!" ?

No, the process also shuts down, then starts again via Epic. Injection occurs only when the game is already running, but still does not work

**Comment by Samlis** [comment]
So #1 fails? You have to be very specific as to which scenario is happening. Point is to inject into that AI.exe at the right time (there's a narrow window for some reason) but if AI.exe crashes after execution from command-line then I can't do anything about it.

**Comment by Egor179** [comment]
And if you do a timeout?

cmd /C "D:\Games\Epic Games\Games\AlienIsolation\AI.exe"
timeout.exe /t 10
for /l %%x in (1, 1, 1) do aliasIsolationInjector.exe

**Comment by Egor179** [comment]
https://youtu.be/0Negn00ft9U

**Comment by Samlis** [comment]
Yes, I tried that but then it's too late. For some reason it won't inject after the AI.exe has been already running for a few seconds. In my testing it was a very small window to inject - too early and too late and it didn't work. I don't know why but the loop solved it.

**Comment by Egor179** [comment]
YES! I finally succeeded :)
I think for prevention you need to increase from 30 to at least 150 injection attempts
https://youtu.be/ihGguCbaQmc

**Comment by Samlis** [comment]
lol, yes, I might have to, since everyone's system might run it at different speeds. I will upload a new ZIP based on our findings here. Thanks a lot for trying and glad it works :D
