### ISSUE TITLE
This game could be played without the Epic Games Store open by using the "-EpicPortal" command line argument. It disables the DRM. (note added later: Ignore this - I was wrong.)

### ISSUE THREAD

**Issue by ancient-animal** [Samlis/AliasIsolationForEpicGamesStore#3]
I right-clicked the executable file of this game (AI.exe) and clicked "Create Shortcut". Then, I right-clicked the Shortcut, then I clicked "Properties", and I changed the "Target" parameter like this:

`"C:\Program Files\Epic Games\AlienIsolation\AI.exe" -EpicPortal`

That allows the game to work without DRM, so the Epic Games Store won't be needed. I hated seeing the disgusting chat window that appeared every time I started this game. That chat window won't appear with the "-EpicPortal" argument.

I decided to write this here in case it helps the designer of this TAA Anti-Aliasing tool. I haven't tried this mod yet. I hope it will work while using the "-EpicPortal" argument and keeping the Epic Games Store closed.

**Comment by ancient-animal** [comment]
I solved the problem! I can play the game without the Epic Games Store open!

This is what I did:

1. I created a backup of the "epicisolation.cmd" file from this mod by renaming it as "epicisolation - original.cmd".

2. I created a new file called "epicisolation - without DRM.cmd".

3. I opened that new file with a text-editing program, and I put these lines inside of it:
```
start /b /d "C:\Program Files\Epic Games\AlienIsolation\" AI.exe -EpicPortal
for /l %%x in (1, 1, 1) do aliasIsolationInjector.exe
```

4. Then I saved the file, and I double-clicked it to activate it.

That caused the mod to work without the Epic Games Store being open! The game is much better now! I'm surprised that the people who created this game didn't add a good anti-aliasing method before they released it!

Remember this:
My "AI.exe" file is in my "C:\Program Files\Epic Games\AlienIsolation\\" directory. If your game is in a different directory, you must change that line in your "epicisolation - without DRM.cmd" file.

**Comment by Samlis** [comment]
oh, thanks. I will add this option to the instructions. Glad it is working for you.

**Comment by ancient-animal** [comment]
I discovered that we can't load our saved progress while playing this game without the Epic Games Store. I read messages from other people that mentioned the same problem. Another person said this, but I haven't verified it: "a main objective near the very beginning will not trigger if you run it without the Epic client".

I'm feeling sorry about my excitement, but your mod still works for me while leaving the Epic Games Store open. I thought the company gave us a gift without DRM.

**Comment by Samlis** [comment]
Thanks for letting me know. Closing this then.
