### ISSUE TITLE
Error when starting the game

### ISSUE THREAD

**Issue by ErdeiFarkasGyula** [Samlis/AliasIsolationForEpicGamesStore#9]
After starting the game I get an error: CreateDirect3D11SurfaceFromDXGISurface 
:(

![image](https://user-images.githubusercontent.com/69863086/235676303-1ce57bdf-3865-48a4-a5c1-3089fad74d2e.png)
![image](https://user-images.githubusercontent.com/69863086/235676685-cf78a43b-529c-4fef-8694-81779132c244.png)

**Comment by Egor179** [comment]
Man, all the solutions are written on the main page

**Comment by ErdeiFarkasGyula** [comment]
Bro, I tried that. Still doesn't work.
